config/routes.rb
Rails.application.routes.draw do
  resources :stories
  root 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  def index
    @stories = Story.all
  end

  # GET /stories/1
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stories/1
  def update
    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stories/1
  def destroy
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def story_params
      params.require(:story).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevopsRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.content %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @story.content %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>